export const CATEGORIES = ['Detox', 'Energize', 'Wellness', 'Performance'] as const

export const INGREDIENTS = [
'Bayam',
  'Kale',
  'Seledri',
  'Jahe',
  'Lemon',
  'Apel',
  'Jeruk',
  'Wortel',
  'Mangga',
  'Kunyit',
  'Nanas',
  'Bit',
  'Blueberry',
  'Acai',
  'Delima',
  'Anggur',
  'Pisang',
  'Selai almond',
  'Kurma',
  'Susu kelapa',
  'Kelapa',
  'Markisa',
  'Jeruk nipis',
  'Madu',
  'Bawang putih',
  'Lavender',
  'Ashwagandha',
  'Jeruk bali',
  'Peterseli',
  'Mentimun',
  'Stroberi',
  'Blackberry',
]

export const HEALTH_GOALS = [
  'Detoksifikasi alami',
  'Manajemen berat badan',
  'Melancarkan pencernaan',
  'Meningkatkan energi',
  'Sistem kekebalan tubuh',
  'Kesehatan mata',
  'Sirkulasi darah',
  'Kesehatan jantung',
  'Performa fisik',
  'Kesehatan otak',
  'Kesehatan kulit',
  'Anti-penuaan',
  'Pembentukan otot',
  'Performa atletis',
  'Pemulihan tubuh',
  'Pencernaan sehat',
  'Energi instan',
  'Penyembuhan flu',
  'Daya tahan tubuh',
  'Kesehatan tenggorokan',
  'Tekanan darah stabil',
  'Hidrasi tubuh',
  'Menurunkan kolesterol',
  'Kesegaran harian',
  'Diet sehat',
  'Pencernaan lancar',
  'Daya ingat',
  'Nutrisi kulit',
  'Pemulihan stamina',
  'Meningkatkan imunitas',
  'Pencegahan sakit',
]

export const SITE_NAME = 'Nadhifa Juice Catalog'
export const SITE_TAGLINE = 'Premium Cold-Pressed Juice Catalog'

export const CTA_TEXT = {
  viewProducts: 'Lihat Produk',
  orderNow: 'Pesan Sekarang',
  addToCart: 'Pesan by WA',
  learnMore: 'Pelajari Lebih',
  closeModal: 'Tutup',
}
