import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Apel Nanas Lemon Jahe Kunyit',
    category: 'Detox',
    price: 23000,
    image: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg',
    ingredients: ['Apel', 'Nanas', 'Lemon', 'Jahe', 'Kunyit'],
    benefits: ['Mendukung fungsi hati', 'Detoksifikasi alami', 'Meningkatkan energi', 'Kaya antioksidan'],
    healthGoals: ['Detoksifikasi', 'Manajemen berat badan', 'Melancarkan pencernaan'],
    description: 'Kombinasi kuat buah apel dan nanas dengan sensasi hangat jahe kunyit serta kesegaran lemon untuk membuang racun tubuh secara alami.',
    servingSize: '250ml',
    caloriesPerServing: 95,
    vitaminC: '150mg',
    potassium: '320mg',
    sugar: '12g',
    rating: 4.8,
    reviews: 342
  },
  {
    id: '2',
    name: 'Wortel Apel Nanas Lemon Jahe',
    category: 'Energize',
    price: 22000,
    image: 'https://images.pexels.com/photos/1337825/pexels-photo-1337825.jpeg',
    ingredients: ['Wortel', 'Apel', 'Nanas', 'Lemon', 'Jahe'],
    benefits: ['Energi alami', 'Menjaga imun tubuh', 'Anti-inflamasi', 'Menyegarkan pikiran'],
    healthGoals: ['Meningkatkan energi', 'Sistem kekebalan tubuh', 'Kesehatan mata'],
    description: 'Kaya akan vitamin dan nutrisi alami dari wortel dan apel, memberikan energi tambahan untuk aktivitas harianmu tanpa lemas.',
    servingSize: '250ml',
    caloriesPerServing: 110,
    vitaminC: '180mg',
    potassium: '410mg',
    sugar: '14g',
    rating: 4.6,
    reviews: 298
  },
  {
    id: '3',
    name: 'Bit Apel Lemon',
    category: 'Wellness',
    price: 23000,
    image: 'https://images.pexels.com/photos/775032/pexels-photo-775032.jpeg',
    ingredients: ['Buah Bit', 'Apel', 'Lemon'],
    benefits: ['Melancarkan sirkulasi darah', 'Anti-inflamasi', 'Meningkatkan stamina', 'Kesehatan jantung'],
    healthGoals: ['Sirkulasi darah', 'Kesehatan jantung', 'Performa fisik'],
    description: 'Campuran premium buah bit merah dan apel fuji pilihan dengan perasan lemon untuk mendukung kesehatan kardiovaskular secara alami.',
    servingSize: '250ml',
    caloriesPerServing: 105,
    vitaminC: '140mg',
    potassium: '480mg',
    sugar: '16g',
    rating: 4.7,
    reviews: 267
  },
  {
    id: '4',
    name: 'Kale Apel Timun Nanas',
    category: 'Wellness',
    price: 24500,
    image: 'https://images.pexels.com/photos/775032/pexels-photo-775032.jpeg',
    ingredients: ['Kale', 'Apel', 'Timun', 'Nanas'],
    benefits: ['Kaya antioksidan', 'Kesehatan otak', 'Kesehatan kulit', 'Anti-aging'],
    healthGoals: ['Kesehatan otak', 'Kesehatan kulit', 'Anti-penuaan'],
    description: 'Superfood jus hijau dari sayur kale dan timun yang segar, kaya akan antioksidan untuk mendukung kesehatan kulit dan fungsi kognitif.',
    servingSize: '250ml',
    caloriesPerServing: 85,
    vitaminC: '210mg',
    potassium: '390mg',
    sugar: '9g',
    rating: 4.9,
    reviews: 421
  },
  {
    id: '5',
    name: 'Kurma Almond',
    category: 'Performance',
    price: 18000,
    image: 'https://images.pexels.com/photos/775032/pexels-photo-775032.jpeg',
    ingredients: ['Kurma premium', 'Kacang Almond', 'Air murni'],
    benefits: ['Pemulihan otot', 'Energi tahan lama', 'Padat nutrisi', 'Kaya protein alami'],
    healthGoals: ['Pembentukan otot', 'Performa atletis', 'Pemulihan tubuh'],
    description: 'Minuman bernutrisi tinggi perpaduan susu almond dan manisnya kurma murni, sangat cocok untuk pemulihan energi setelah berolahraga.',
    servingSize: '250ml',
    caloriesPerServing: 240,
    vitaminC: '10mg',
    potassium: '380mg',
    sugar: '18g',
    rating: 4.7,
    reviews: 189
  },
  {
    id: '6',
    name: 'Nanas Madu Murni',
    category: 'Energize',
    price: 22000,
    image: 'https://images.pexels.com/photos/5946630/pexels-photo-5946630.jpeg',
    ingredients: ['Nanas Madu Murni'],
    benefits: ['Meningkatkan imun', 'Enzim pencernaan alami', 'Kesehatan kulit', 'Menyegarkan badan'],
    healthGoals: ['Pencernaan sehat', 'Energi instan', 'Kesehatan kulit'],
    description: 'Kesegaran murni dari 100% nanas madu tanpa tambahan air, kaya akan enzim bromelain untuk membantu melancarkan pencernaan.',
    servingSize: '250ml',
    caloriesPerServing: 115,
    vitaminC: '240mg',
    potassium: '290mg',
    sugar: '20g',
    rating: 4.5,
    reviews: 234
  },
  {
    id: '7',
    name: 'Anti Batuk Flu Shot',
    category: 'Wellness',
    price: 15000,
    image: 'https://images.pexels.com/photos/5946973/pexels-photo-5946973.jpeg',
    ingredients: ['Jahe emprit', 'Kunyit', 'Lemon', 'Madu'],
    benefits: ['Meredakan batuk', 'Meredakan gejala flu', 'Antimikroba alami', 'Menghangatkan tenggorokan'],
    healthGoals: ['Penyembuhan flu', 'Daya tahan tubuh', 'Kesehatan tenggorokan'],
    description: 'Konsentrat jamu herbal alami berukuran mini yang dirancang khusus untuk mempercepat pemulihan gejala batuk, pilek, dan radang tenggorokan.',
    servingSize: '100ml',
    caloriesPerServing: 45,
    vitaminC: '300mg',
    potassium: '180mg',
    sugar: '6g',
    rating: 4.8,
    reviews: 376
  },
  {
    id: '8',
    name: 'Celery Apel Timun Jahe',
    category: 'Wellness',
    price: 24500,
    image: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg',
    ingredients: ['Celery Stick (Seledri)', 'Apel', 'Timun', 'Jahe'],
    benefits: ['Meredakan stres', 'Menurunkan darah tinggi', 'Detoksifikasi tubuh', 'Efek relaksasi'],
    healthGoals: ['Kesehatan jantung', 'Tekanan darah stabil', 'Hidrasi tubuh'],
    description: 'Kombinasi seledri stik impor dengan apel segar dan timun untuk membantu menurunkan tekanan darah serta merilekskan tubuh.',
    servingSize: '250ml',
    caloriesPerServing: 65,
    vitaminC: '120mg',
    potassium: '550mg',
    sugar: '7g',
    rating: 4.6,
    reviews: 198
  },
  {
    id: '9',
    name: 'Belimbing Apel Nanas',
    category: 'Energize',
    price: 22000,
    image: 'https://images.pexels.com/photos/1337824/pexels-photo-1337824.jpeg',
    ingredients: ['Belimbing', 'Apel', 'Nanas'],
    benefits: ['Kaya vitamin C', 'Kesehatan kulit wajah', 'Menurunkan kolesterol', 'Antioksidan tinggi'],
    healthGoals: ['Kesehatan kulit', 'Menurunkan kolesterol', 'Kesegaran harian'],
    description: 'Paduan rasa unik dari buah belimbing manis lokal dicampur apel dan nanas segar untuk menjaga kelembapan kulit Anda.',
    servingSize: '250ml',
    caloriesPerServing: 88,
    vitaminC: '190mg',
    potassium: '280mg',
    sugar: '13g',
    rating: 4.4,
    reviews: 267
  },
  {
    id: '10',
    name: 'Pokcoy Pir Nanas',
    category: 'Detox',
    price: 22000,
    image: 'https://images.pexels.com/photos/5946643/pexels-photo-5946643.jpeg',
    ingredients: ['Sayur Pokcoy', 'Buah Pir', 'Nanas'],
    benefits: ['Pencernaan lancar', 'Detoksifikasi usus', 'Rendah kalori', 'Padat serat alami'],
    healthGoals: ['Diet sehat', 'Detoksifikasi alami', 'Pencernaan lancar'],
    description: 'Jus sayur pokcoy segar yang tidak pahit berkat kombinasi manis dari buah pir dan asam segar buah nanas.',
    servingSize: '250ml',
    caloriesPerServing: 78,
    vitaminC: '160mg',
    potassium: '340mg',
    sugar: '10g',
    rating: 4.7,
    reviews: 312
  },
  {
    id: '11',
    name: 'Strawberry Apel Pir',
    category: 'Wellness',
    price: 24500,
    image: 'https://images.pexels.com/photos/839725/pexels-photo-839725.jpeg',
    ingredients: ['Strawberry', 'Apel', 'Buah Pir'],
    benefits: ['Kesehatan mata', 'Meningkatkan memori', 'Antioksidan tinggi', 'Konsentrasi'],
    healthGoals: ['Kesehatan mata', 'Daya ingat', 'Nutrisi kulit'],
    description: 'Kombinasi buah strawberry berry segar yang manis asam dengan apel dan pir, memberikan perlindungan antioksidan maksimal bagi tubuh.',
    servingSize: '250ml',
    caloriesPerServing: 98,
    vitaminC: '240mg',
    potassium: '310mg',
    sugar: '12g',
    rating: 4.8,
    reviews: 289
  },
  {
    id: '12',
    name: 'Jambu Merah Murni (1 Liter)',
    category: 'Performance',
    price: 40000,
    image: 'https://images.pexels.com/photos/5947019/pexels-photo-5947019.jpeg',
    ingredients: ['Jambu Biji Merah Murni'],
    benefits: ['Menaikkan trombosit', 'Mencegah demam berdarah', 'Kaya vitamin C', 'Kesehatan pencernaan'],
    healthGoals: ['Pemulihan stamina', 'Meningkatkan imunitas', 'Pencegahan sakit'],
    description: '100% jus jambu biji merah murni ukuran ekonomis 1 Liter. Sangat baik untuk menjaga stamina keluarga dan meningkatkan kadar trombosit tubuh.',
    servingSize: '1000ml',
    caloriesPerServing: 380,
    vitaminC: '650mg',
    potassium: '820mg',
    sugar: '45g',
    rating: 4.9,
    reviews: 234
  }
]